# Generated by Django 4.0 on 2022-02-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
